# Generated by Django 3.1.5 on 2021-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20210311_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
